### ISSUE TITLE
Buttons not working in Firefox

### ISSUE THREAD

**Issue by Rich2** [Rich2/openstrat#210]
Buttons not working in Firefox

**Comment by w0d** [comment]
need source map for the scalajs build but
after updating project to latest tried to build js with  JsDev/fullOptJS
etcbut no joysbt:OpenStrat>Dev/fullOptJS error No such setting/task 

also documentation on website fail

    On Tuesday, 14 February 2023 at 14:24:36 GMT, Rich ***@***.***> wrote:  
 
 


Assigned #210 to @w0d.

**Comment by w0d** [comment]
tiz verking now..
