### ISSUE TITLE
Web page generation, begin PaintElems to SVG and package ostrat.pWeb

### ISSUE THREAD

**Issue by Rich2** [Rich2/openstrat#24]
I'm not sure if this code's long term existence is justified. I'm not sure if it provides sufficient advantage over using a library, maybe Scala-tags, maybe something else. I've had a closer look at Scala-tags and I don't find it succinct enough.

Most of the code was written before I aware of Scala-tags existence. I'm not sure if I can give it the time and focus that it would need. However I have been using this code regularly for web site generation. I'm not sure if it can and should be integrated with my RSON (Rich Succinct Object notation) as part of a hierarchical code / data abstraction, generation and manipulation.

I am very happy with my RSON, although it needs significant development and I'm not sure about the the first word of the name.

**Comment by w0d** [comment]
Rich Succinct Object Notation works on lots of levels initialism, marsupial, anagram and plenty more but not palindrome or recursive acronym :(

**Comment by Rich2** [comment]
So the code is being rewritten, with the old code taken out of the src tree, with a view to its short term deletion.
