### ISSUE TITLE
Tile addition and appalling performance in the worlds maps

### ISSUE THREAD

**Issue by Rich2** [Rich2/openstrat#25]
Although designed with performance very much in mind. Area selection and reduced object generation at small scales, has not been implemented.

Part of this is implementing adjacent tile addition. I think I want to implement #26 before dealing with this.

**Comment by richtype** [comment]
I commit to implementing this by the end of 2019.

**Comment by Rich2** [comment]
So this is waiting on the completion of #127.

**Comment by Rich2** [comment]
Closing this into #155.
