### ISSUE TITLE
Refine ptInside method on ClickShapeTr trait

### ISSUE THREAD

**Issue by Rich2** [Rich2/openstrat#4]
So currently arcs and beziers are being treated as straight lines.

**Comment by w0d** [comment]
arcs should be straight forward using polar coords at least.
a slow way for beziers could be to draw it in a buffer and do a color test on the point in question.
if you draw a line in any direction from the test/hit point and count the number of times it crosses the boundary of the path - if its odd then its inside.

**Comment by Rich2** [comment]
This will also be merged into #120.
