### ISSUE TITLE
TextGraphic fields

### ISSUE THREAD

**Issue by Rich2** [Rich2/openstrat#42]
Possible additional fields required for TextGraphic and TextOutline, in particular baseLine.

**Comment by w0d** [comment]
early november job for mes :+1:

**Comment by w0d** [comment]
@Rich2 are you drawn to utilising **Bold**/_Itallics_ if so weights could also be an option

**Comment by Rich2** [comment]
@w0d I'd say for now just go for parity with what ever Web Canvas offers for test.

**Comment by w0d** [comment]
baseLine: BaseLine [ TopBL | MiddleBL | AlphabeticBL | BottomBL ]
to do bold & italic doesn't make sense timewise and I'd rather put time for other issues.

**Comment by w0d** [comment]
re [5b0e1bb](https://github.com/Rich2/openstrat/commit/5b0e1bb507798fcf40091455a371c34a3424edfc)
that looks a nicer way - cheers
