### ISSUE TITLE
Simultaneous game turns

### ISSUE THREAD

**Issue by Rich2** [Rich2/openstrat#48]

**Comment by richtype** [comment]
I commit to implementing this by the end of 2019.

**Comment by w0d** [comment]
been trying to help stephen do the georgia flag which features four bolnur-katskhuri crosses 
i was thinking along the lines of:Shape(LineSeg(5 vv 5), ArcSeg(110 vv 0, 10 vv 18), ArcSeg(0 vv 71, -10 vv 18), ArcSeg(-110 vv 0, -10 vv 18), LineSeg(-5 vv 5)).fill(Black)

do you reckon this is the best way to approach it?cheers
