### ISSUE TITLE
Documentation and Issues

### ISSUE THREAD

**Issue by Rich2** [Rich2/openstrat#71]
So currently for documentation, we have a README and some odd text files in misc (miscellaneous), perhaps that folder name should be changed. This has served us well for initial development, but I think we now need a properly linked and integrated multi-file documentation / wiki. Not quite sure how that should fit with the README, perhaps that can be an overview with links to html files with more detailed examination / explanation of topics.

So I am of strongly of the view that Github issues, I will hence forth refer to them as Gissues, should be actionable and achievable within a fixed time frame work given our currently level of developer time resources. I would suggest a time period of no more than a year, but I am tempted to go for 3 months. As the project grows in collaborators, the time frame should be increased, but given the current size of the team, I don't think its advantageous to have Gissues having around for more than 3 months.

Longer term issues and longer term feature requests / aspirations belong in the documentation, perhaps under a section called "Roadmaps, priorities and narcissistic fantasies". Quick questions can make good Gissues, but they can be resolved and closed by putting the answer in the documentation.

Going forward it could be helpful to assign roles even before we launch as a formal organisation. Roles should be in the documentation. One role stands out: "Lead Platforms Developer". At least for me this is not a fun area of the project, but I feel its a very good thing to put on a CV. I had thought that the different platforms could be divided up in terms of responsibilities, but I now realise that the responsibilities need to be bundled together. The different platform implementations need to be developed in tandem with the evolution of cross platform interfaces.

This issue itself should be looked to be closed fairly promptly, with resulting useful decisions having gone into the documentation.

**Comment by richtype** [comment]
As a temporary measure I've just added a Road Map priorities section at the end of the README.

**Comment by richtype** [comment]
Remove priority level from the issues. Priority sequencing should be in the road map.

**Comment by w0d** [comment]
your offer of something to put on my cv is worthless as i dont have one

i could help in some respects but i imagine i dont know scala enough to put my hand up

**Comment by Rich2** [comment]
So this issue is no longer useful.
