### ISSUE TITLE
loadFile restricted functionality

### ISSUE THREAD

**Issue by w0d** [Rich2/openstrat#80]
`loadFile` from CanvasPlatform.scala will only attempt to load a file called "test" regardless of the filename passed

eg: `val loadData = canv.loadFile("myDataFile.txt")`

Fails silently with SBT output:

> Bad(List(FilePosn(Java Exception,1,1)/home/thisUser/AppData/Local/OpenStratData/test (No such file or directory)))

renaming the file to "test" then successfully loads the data

tried resolving following the hierarchy which drew a blank and also tried searching for test which wasn't the nicest term to search for ;)

**Comment by Rich2** [comment]
I'm folding this into #133 for the time being,as it may be related.
